      SUBROUTINE DELK0 ( EV2K   , ESTR   , VALSYM , VALASY ,
     1                   SMAT   , HMAT   , NOFSET , NDIMST ,
     1                   JP1    , IRODIM , IEO    , ITAU   ,
     1                   INTSYM , INTASY , ISTOFF ,
     1                   STOREM , NOPERA )
C
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 M1,M2,M3,M,U1,U3,U13,V,RHO,EPS,
     1      CR,SR,CSE,SNE,
     2      CRE,SRE,CORO,EPSP,EPSPP,EPSPPP
C
      REAL*8 AMASS(3,12)
C
      REAL*8 RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1       AA1,AA3,
     2       F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3       F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4       F13,F1A13,F2A13,F3A13,
     5       F111,F1A111,F2A111,F333,F1A333,F2A333,
     6       F113,F1A113,F2A113,F133,F1A133,F2A133,
     7       F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8       F1333,FA1333,F1133,FA1133,
     8       RE12 , RE32 , RHOREF , VMIN
C
      REAL*8 ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1      PREC
C
      REAL*8 THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1      THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2      VELLGT , PLANCK , AVOGNO , DEGRAD , RADDEG ,
     3      PI
C
      REAL*8   B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      REAL*8   CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
      INTEGER NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 , NFIL6 ,
     5       NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6       NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7       NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6       ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7       IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8       NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER,
     9       ISOMAX , NATTS  , V0TYPE , IVAR(55) , PARMAX ,
     1       NUMPAR , PRTINT
C
      INTEGER V1 ,V2, V3 , V2MXP1, V2P1,
     1       NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2       NSEPP2 , NSEQP1 , MBASIS ,
     3       MDIM , NFSYM0, NFASY0, NFSYMJ, NFASYJ,
     4       KSTYPA(2) , LSTYPA(2) , JMAX , V2MAX , JMAXP1
C
      INTEGER IQUANT(5,12)
C
      LOGICAL SYMM
C
      REAL*8 RMK(2),AAS(2)
      INTEGER NOBAS,MBASP1,LENIW
      INTEGER LENINT,IOSC1,IOSC3,I,J,IR,JL
      REAL*8 G,GC1,GC3,GC1113,GC3133,GC1133,GC3113
      REAL*8  EV2K(V2MXP1,JMAXP1),ESTR(NOBAS),
     1       SMAT(NOBAS,NOBAS),VALSYM(INTSYM),VALASY(INTASY),
     1       HMAT(IRODIM,IRODIM),STOREM(NOBAS,NOBAS,NOPERA)
      REAL*8  CONCOR,CONFC1,CONG11,CONG33,CONG13,CORHOE
      COMMON /ISOTOP/ IQUANT,AMASS
C
      COMMON /VALUES/ RHO,EPS,EPSP,EPSPP,EPSPPP,
     1               CR,SR,CSE,SNE,CRE,SRE,CORO
C
      COMMON /MOLCUL/ RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1               AA1,AA3,
     2               F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3               F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4               F13,F1A13,F2A13,F3A13,
     5               F111,F1A111,F2A111,F333,F1A333,F2A333,
     6               F113,F1A113,F2A113,F133,F1A133,F2A133,
     7               F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8               F1333,FA1333,F1133,FA1133,
     8               RE12 , RE32 , M1 , M2 , M3 , M ,
     9               U1 , U3 , U13 , V ,
     1               SYMM
C
      COMMON /INTEG/  ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1               RHOREF , VMIN , V0TYPE ,
     1               NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2               NSEPP2 , NSEQP1 , KSTYPA , LSTYPA
C
      COMMON /DIMEN/  MBASIS ,  V2MAX  , V2MXP1 ,
     1               JMAX   , JMAXP1 , MDIM   , NFSYM0 , NFASY0 ,
     2               NFSYMJ , NFASYJ
C
      COMMON /LSFIT/  PARMAX , NUMPAR , ISOMAX , IVAR
C
      COMMON /SYS/    THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1                     THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2                     VELLGT , PLANCK , AVOGNO , PI , PREC ,
     4                     NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 ,
     5                     NFIL6 , NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6                     NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7                     NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6                     ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7                     IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8                     NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER ,
     9                       NATTS , PRTINT
C
      COMMON/BCOEFF/
     1      B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      COMMON/CRCOEF/
     1      CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
C
      COMMON/MORSE/RMK,AAS
      COMMON/MODIM/NOBAS,MBASP1,LENIW
C
      CONCOR=PLANCK*AVOGNO*1.0D+16/(1.6D+01*PI*PI*VELLGT)
      CONRR=2.0D+00*CONCOR
      CONXX=CONCOR
      CONZZ=2.0D+00*CONXX
      CONFC1=2.0D+00*CONCOR
      CONG13=-CONFC1/M2
      J=JP1-1
      CORHOE=DCOS(RHOE)
      REWIND NFIL9
      IF (.NOT. SYMM) REWIND NFIL10
C
      XJJP1=DFLOAT(J*JP1)
      IF (MOD(J+ITAU,2) .NE. 0) XJJP1=-XJJP1
C
      DO 940 KP1=1,JP1
      XJK=DFLOAT(J*JP1-(KP1-1)*(KP1-1))
C
      DO 920 INDEX1=1,V2MXP1
      DO 900 INDEX2=1,V2MXP1
C
      READ (NFIL9 ) (VALSYM(L), L=1,58)
      IF (.NOT. SYMM) READ (NFIL10) (VALASY(L), L=1,41)
      IF (MOD(KP1,2) .EQ. IEO) GOTO 900
      IF (MOD(J+ITAU,2) .NE. 0  .AND. KP1 .EQ. 1)  GOTO 900
C
      NINDEX=0
C
      IF (MOD(KP1,2) .NE. 0) THEN
            INDK=(KP1-1)/2
            IF (MOD(J+ITAU,2) .NE. 0) INDK=INDK-1
      ELSE
            INDK=(KP1-2)/2
      ENDIF
      IROWOF=NOFSET+INDK*V2MXP1*NDIMST+(INDEX1-1)*NDIMST
      ICOLOF=NOFSET+INDK*V2MXP1*NDIMST+(INDEX2-1)*NDIMST
C
C  0. ZERO ORDER ENERGIES ADDED IN DIAGONAL ELEMENTS
C
      IF (INDEX1 .EQ. INDEX2) THEN
      DO  50 IR=1,NDIMST
50    HMAT(IROWOF+IR,IROWOF+IR)=HMAT(IROWOF+IR,IROWOF+IR)
     1       + EV2K(INDEX1,KP1)+ESTR(ISTOFF+IR)
      ENDIF
C
C  1. LEADING TERM (NOT DEPENDING ON STRETCHING COORDINATES)
C     CONTRIBUTIONS FROM:   A. MUXX0+MUYY0
C                           B. CORIOLIS COMMUTATOR TERMS
C                           C. G MATRIX COMMUTATOR TERMS
C                           D. PSEUDOPOTENTIAL TERM
C
      G =  VALSYM(10)
     1 + CONXX*(VALSYM(32)+VALSYM(41))*XJK
      GCOR1= CONCOR*AA1*VALSYM(23)
      IF (SYMM) THEN
            GCOR3=GCOR1
      ELSE
            GCOR3= CONCOR*AA3*VALASY(16)
      ENDIF
      GGMAT=-CONG13*AA1*AA3*VALSYM(22)/2.0D+00
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(32)-VALSYM(41))*XJJP1
      DO 100 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+IR)=HMAT(ICOLOF+IR,IROWOF+IR)
     1                       +GCOR1+GCOR3
100   HMAT(IROWOF+IR,ICOLOF+IR)=HMAT(IROWOF+IR,ICOLOF+IR)
     1                       +G +GCOR1+GCOR3+GGMAT
C
C  2. TERMS CONTAINING Y1
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C                           E. CORIOLIS COMMUTATOR TERMS
C                           F. G MATRIX COMMUTATOR TERMS
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONRR*VALSYM(2)
     1  + VALSYM(11)
     1  + CONXX*(VALSYM(33)+VALSYM(42))*XJK
     2  + CONZZ*VALSYM(51)
      GCOR1=-CONCOR*AA1*VALSYM(23)
     1     + 2.0D+00*CONCOR*AA1*VALSYM(25)
      IF (SYMM) THEN
            GCOR3= CONCOR*AA1*VALSYM(27)
      ELSE
            GCOR3= CONCOR*AA3*VALASY(19)
      ENDIF
      GGMAT=CONG13*AA1*AA3*VALSYM(22)/2.0D+00
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(33)-VALSYM(42))*XJJP1
      DO 120 JL=1,NDIMST
      DO 120 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
120   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                 +(GGMAT+G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 3. TERMS CONTAINING Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) THEN
                      G = CONRR*VALASY(1)
     1                  + VALASY(7)
     2                  + CONXX*(VALASY(24)+VALASY(30))*XJK
     3                  + CONZZ*VALASY(36)
                      GCOR1= CONCOR*AA1*VALSYM(27)
                      GCOR3=-CONCOR*AA3*VALASY(16)
     1                     +2.0D+00*CONCOR*AA3*VALASY(18)
      ENDIF
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(24)-VALASY(30))*XJJP1
      DO 140 JL=1,NDIMST
      DO 140 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
140   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                 +(GGMAT+G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C  4. TERMS CONTAINING Y1*Y1
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C                           E. CORIOLIS COMMUTATOR TERMS
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONRR*VALSYM(3)
     1  + VALSYM(12)
     1  + CONXX*(VALSYM(34)+VALSYM(43))*XJK
     2  + CONZZ*VALSYM(52)
      GCOR1=-2.0D+00*CONCOR*AA1*VALSYM(25)
     1     +3.0D+00*CONCOR*AA1*VALSYM(28)
      IF (SYMM) THEN
            GCOR3= CONCOR*AA1*VALSYM(31)
      ELSE
            GCOR3= CONCOR*AA3*VALASY(22)
      ENDIF
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(34)-VALSYM(43))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F11
      DO 160 JL=1,NDIMST
      DO 160 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
160   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 5. TERMS CONTAINING Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) THEN
                      G = CONRR*VALASY(2)
     1                  + VALASY(8)
     2                  + CONXX*(VALASY(25)+VALASY(31))*XJK
     3                  + CONZZ*VALASY(37)
                    GCOR1= CONCOR*AA1*VALSYM(31)
                    GCOR3=-2.0D+00*CONCOR*AA3*VALASY(18)
     1                   +3.0D+00*CONCOR*AA3*VALASY(21)
      IF (INDEX1 .EQ. INDEX2) G = G - F33
      ENDIF
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(25)-VALASY(31))*XJJP1
      DO 180 JL=1,NDIMST
      DO 180 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
180   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 6. TERMS CONTAINING Y1*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONRR*VALSYM(4)
     1  + VALSYM(13)
     2  + CONXX*(VALSYM(35)+VALSYM(44))*XJK
     3  + CONZZ*VALSYM(53)
      GCOR1=-CONCOR*AA1*VALSYM(27)
     1     +2.0D+00*CONCOR*AA1*VALSYM(30)
      IF (SYMM) THEN
            GCOR3=GCOR1
      ELSE
            GCOR3=-CONCOR*AA3*VALASY(19)
     1           +2.0D+00*CONCOR*AA3*VALASY(23)
      ENDIF
      GGMAT=-CONG13*AA1*AA3*VALSYM(22)/2.0D+00
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(35)-VALSYM(44))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F13
      DO 200 JL=1,NDIMST
      DO 200 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
200   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                 +(GGMAT+G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C  7. TERMS CONTAINING Y1*Y1*Y1
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C                           E. CORIOLIS COMMUTATOR TERMS
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONRR*VALSYM(5)
     1  + VALSYM(14)
     1  + CONXX*(VALSYM(36)+VALSYM(45))*XJK
     2  + CONZZ*VALSYM(54)
      GCOR1=-3.0D+00*CONCOR*AA1*VALSYM(28)
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(36)-VALSYM(45))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F111
      DO 220 JL=1,NDIMST
      DO 220 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       +GCOR1*SMAT(ISTOFF+IR,ISTOFF+JL)
220   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GCOR1)*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 8. TERMS CONTAINING Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) THEN
                      G = CONRR*VALASY(3)
     1                  + VALASY(9)
     2                  + CONXX*(VALASY(26)+VALASY(32))*XJK
     3                  + CONZZ*VALASY(38)
                    GCOR1=-3.0D+00*CONCOR*AA3*VALASY(21)
      IF (INDEX1 .EQ. INDEX2) G = G - F333
      ENDIF
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(26)-VALASY(32))*XJJP1
      DO 240 JL=1,NDIMST
      DO 240 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       +GCOR1*SMAT(ISTOFF+IR,ISTOFF+JL)
240   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GCOR1)*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C  9. TERMS CONTAINING Y1*Y1*Y3
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C                            E. CORIOLIS COMMUTATOR TERMS
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONRR*VALSYM(6)
     1  + VALSYM(15)
     1  + CONXX*(VALSYM(37)+VALSYM(46))*XJK
     2  + CONZZ*VALSYM(55)
      GCOR1=-2.0D+00*CONCOR*AA1*VALSYM(30)
      IF (SYMM) THEN
            GCOR3=-CONCOR*AA1*VALSYM(31)
      ELSE
            GCOR3=-CONCOR*AA3*VALASY(22)
      ENDIF
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(37)-VALSYM(46))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F113
      DO 260 JL=1,NDIMST
      DO 260 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
260   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 10. TERMS CONTAINING Y1*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) THEN
                      G = CONRR*VALASY(4)
     1                  + VALASY(10)
     2                  + CONXX*(VALASY(27)+VALASY(33))*XJK
     3                  + CONZZ*VALASY(39)
                    GCOR3=-2.0D+00*CONCOR*AA3*VALASY(23)
                    GCOR1=-CONCOR*AA1*VALSYM(30)
      IF (INDEX1 .EQ. INDEX2) G = G - F133
      ENDIF
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(27)-VALASY(33))*XJJP1
      DO 280 JL=1,NDIMST
      DO 280 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
280   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                   +(G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C  11. TERMS CONTAINING Y1*Y1*Y1*Y1
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONRR*VALSYM(7)
     1  + VALSYM(16)
     1  + CONXX*(VALSYM(38)+VALSYM(47))*XJK
     2  + CONZZ*VALSYM(56)
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(38)-VALSYM(47))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F1111
      DO 300 JL=1,NDIMST
      DO 300 IR=1,NDIMST
300   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 12. TERMS CONTAINING Y3*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = CONRR*VALASY(5)
     1                  + VALASY(11)
     2                  + CONXX*(VALASY(28)+VALASY(34))*XJK
      IF (INDEX1 .EQ. INDEX2 .AND. .NOT. SYMM) G = G - F3333
     3                  + CONZZ*VALASY(40)
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(28)-VALASY(34))*XJJP1
      DO 320 JL=1,NDIMST
      DO 320 IR=1,NDIMST
320   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C  13. TERMS CONTAINING Y1*Y1*Y1*Y3
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONRR*VALSYM(8)
     1  + VALSYM(17)
     1  + CONXX*(VALSYM(39)+VALSYM(48))*XJK
     2  + CONZZ*VALSYM(57)
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(39)-VALSYM(48))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F1113
      DO 340 JL=1,NDIMST
      DO 340 IR=1,NDIMST
340   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 14. TERMS CONTAINING Y1*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = CONRR*VALASY(6)
     1                  + VALASY(12)
     2                  + CONXX*(VALASY(29)+VALASY(35))*XJK
     3                  + CONZZ*VALASY(41)
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(29)-VALASY(35))*XJJP1
      IF (INDEX1 .EQ. INDEX2 .AND. .NOT. SYMM) G = G - F1333
      DO 360 JL=1,NDIMST
      DO 360 IR=1,NDIMST
360   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 15. TERMS CONTAINING Y1*Y1*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONRR*VALSYM(9)
     1  + VALSYM(18)
     2  + CONXX*(VALSYM(40)+VALSYM(49))*XJK
     3  + CONZZ*VALSYM(58)
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(40)-VALSYM(49))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F1133
      DO 380 JL=1,NDIMST
      DO 380 IR=1,NDIMST
380   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 22. TERMS CONTAINING Y1*P1+P1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*VALSYM(23)
      DO 540 JL=1,NDIMST
      DO 540 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
540   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 23. TERMS CONTAINING Y3*P3+P3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = CONCOR*VALASY(16)
      DO 560 JL=1,NDIMST
      DO 560 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
560   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 24. TERMS CONTAINING Y3*P1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = 2.0D+00*CONCOR*VALSYM(24)
      DO 580 JL=1,NDIMST
      DO 580 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
580   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 25. TERMS CONTAINING Y1*P3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*VALASY(15)
      DO 600 JL=1,NDIMST
      DO 600 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
600   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 26. TERMS CONTAINING Y1*Y1*P1+P1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*VALSYM(25)
      DO 620 JL=1,NDIMST
      DO 620 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
620   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 27. TERMS CONTAINING Y3*Y3*P3+P3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = CONCOR*VALASY(18)
      DO 640 JL=1,NDIMST
      DO 640 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
640   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 28. TERMS CONTAINING P1*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = 2.0D+00*CONCOR*VALSYM(26)
      DO 660 JL=1,NDIMST
      DO 660 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
660   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 29. TERMS CONTAINING P3*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*VALASY(17)
      DO 680 JL=1,NDIMST
      DO 680 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
680   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 30. TERMS CONTAINING (Y1*P1+P1*Y1)*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*VALSYM(27)
      DO 700 JL=1,NDIMST
      DO 700 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
700   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 31. TERMS CONTAINING (Y3*P3+P3*Y3)*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = CONCOR*VALASY(19)
      DO 720 JL=1,NDIMST
      DO 720 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
720   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 32. TERMS CONTAINING Y1*Y1*Y1*P1+P1*Y1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*VALSYM(28)
      DO 740 JL=1,NDIMST
      DO 740 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
740   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 33. TERMS CONTAINING Y3*Y3*Y3*P3+P3*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = CONCOR*VALASY(21)
      DO 760 JL=1,NDIMST
      DO 760 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
760   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 34. TERMS CONTAINING P1*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = 2.0D+00*CONCOR*VALSYM(29)
      DO 780 JL=1,NDIMST
      DO 780 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
780   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 35. TERMS CONTAINING P3*Y1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*VALASY(20)
      DO 800 JL=1,NDIMST
      DO 800 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
800   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 36. TERMS CONTAINING (Y1*Y1*P1+P1*Y1*Y1)*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*VALSYM(30)
      DO 820 JL=1,NDIMST
      DO 820 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
820   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 37. TERMS CONTAINING (Y3*Y3*P3+P3*Y3*Y3)*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = CONCOR*VALASY(23)
      DO 840 JL=1,NDIMST
      DO 840 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
840   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 38. TERMS CONTAINING (Y1*P1+P1*Y1)*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*VALSYM(31)
      DO 860 JL=1,NDIMST
      DO 860 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
860   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 39. TERMS CONTAINING (Y3*P3+P3*Y3)*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = CONCOR*VALASY(22)
      DO 880 JL=1,NDIMST
      DO 880 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL)
880   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 16. TERMS CONTAINING P1*P3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = 2.0D+00*CONG13*VALSYM(19)
      IF (INDEX1 .EQ. INDEX2) G = G + 2.0D+00*CONG13*CORHOE
      DO 400 JL=1,NDIMST
      DO 400 IR=1,NDIMST
400   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 17. TERMS CONTAINING Y1*P1*P3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONG13*VALSYM(20)
      DO 420 JL=1,NDIMST
      DO 420 IR=1,NDIMST
420   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 18. TERMS CONTAINING Y3*P1*P3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM) G = CONG13*VALASY(13)
      DO 440 JL=1,NDIMST
      DO 440 IR=1,NDIMST
440   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 19. TERMS CONTAINING Y1*Y1*P1*P3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONG13*VALSYM(21)
      DO 460 JL=1,NDIMST
      DO 460 IR=1,NDIMST
460   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 20. TERMS CONTAINING Y3*Y3*P1*P3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM)  G = CONG13*VALASY(14)
      DO 480 JL=1,NDIMST
      DO 480 IR=1,NDIMST
480   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
C
C 21. TERMS CONTAINING Y1*Y3*P1*P3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONG13*VALSYM(22)/2.0D+00
      DO 500 JL=1,NDIMST
      DO 500 IR=1,NDIMST
500   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL)
900   CONTINUE
920   CONTINUE
940   CONTINUE
      RETURN
      END
