      SUBROUTINE GENSTR (                            IW1    ,
     1                   IW3    , OVER   , TMAT   , ESTR   ,
     1                   SMAT   , VMAT   , WMAT   , STOREM ,
     1                   NOPERA )
C
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 M1,M2,M3,M,U1,U3,U13,V,RHO,EPS,
     1      CR,SR,CSE,SNE,
     2      CRE,SRE,CORO,EPSP,EPSPP,EPSPPP
C
      REAL*8 AMASS(3,12)
C
      REAL*8 RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1       AA1,AA3,
     2       F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3       F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4       F13,F1A13,F2A13,F3A13,
     5       F111,F1A111,F2A111,F333,F1A333,F2A333,
     6       F113,F1A113,F2A113,F133,F1A133,F2A133,
     7       F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8       F1333,FA1333,F1133,FA1133,
     8       RE12 , RE32 , RHOREF , VMIN
C
      REAL*8 ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1      PREC
C
      REAL*8 THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1      THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2      VELLGT , PLANCK , AVOGNO , DEGRAD , RADDEG ,
     3      PI
C
      REAL*8   B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      REAL*8   CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
      INTEGER NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 , NFIL6 ,
     5       NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6       NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7       NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6       ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7       IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8       NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER,
     9       ISOMAX , NATTS  , V0TYPE , IVAR(55) , PARMAX ,
     1       NUMPAR , PRTINT
C
      INTEGER V1 ,V2, V3 , V2MXP1, V2P1,
     1       NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2       NSEPP2 , NSEQP1 , MBASIS ,
     3       MDIM , NFSYM0, NFASY0, NFSYMJ, NFASYJ,
     4       KSTYPA(2) , LSTYPA(2) , JMAX , V2MAX , JMAXP1
C
      INTEGER IQUANT(5,12)
C
      LOGICAL SYMM
C
      REAL*8 RMK(2),AAS(2)
      INTEGER NOBAS,MBASP1,LENIW
      INTEGER        IOSC1,IOSC3,I,J,IR,JL
      REAL*8 G,GC1,GC3,GC1113,GC3133,GC1133,GC3113
      INTEGER IW1(LENIW),IW3(LENIW),V2L,V2R,ISTA1,ISTA3,IJMP1,
     1       IJMP3,IR1,IR3,IR11,IR33,IR13,IR111,IR333,IR113,IR133,
     2       IR1111,IR3333,IR1113,IR1333,IR1133,
     3       IV1,IV3,IV11,IV33,IV13,IV111,IV333,IV113,IV133,
     4       IV1111,IV3333,IV1113,IV1333,IV1133,
     5       IG0,IG1,IG3,IG11,IG33,IG13,
     6       IC11,IC33,IC13,IC31,IC111,IC333,IC133,IC311,
     7       IC113,IC313,IC1111,IC3333,IC1333,IC3111,IC1113,
     8       IC3133,IC1133,IC3113
      INTEGER INDEXL,INDEXR,IOFFS,JOFFS,INDVVP,INDPVV,
     1       LABELA,LABELB,LABELC,LVP1,LVP3,LPV1,LPV3,
     2       LVP11,LVP33,LPV11,LPV33,LVP13,LPV13,
     3       LVP111,LVP333,LPV111,LPV333,LVP113,LPV113,
     4       LVP133,LPV133,LABVVP,LABPVV
      INTEGER DIMA,KSTYP1,KSTYP2,LSTYP1,LSTYP2,IOFFSA,JOFFSA,
     1       IOFFSB,JOFFSB
      REAL*8                                     OVER(2,MBASP1,MBASP1),
     1       ESTR(NOBAS),TMAT(NOBAS,NOBAS),
     1       SMAT(NOBAS,NOBAS),WMAT(NOBAS,NOBAS),
     1       VMAT(NOBAS,NOBAS),STOREM(NOBAS,NOBAS,NOPERA)
      REAL*8  CONCOR,CONFC1,CONG11,CONG33,CONG13,CORHOE
      COMMON /ISOTOP/ IQUANT,AMASS
C
      COMMON /VALUES/ RHO,EPS,EPSP,EPSPP,EPSPPP,
     1               CR,SR,CSE,SNE,CRE,SRE,CORO
C
      COMMON /MOLCUL/ RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1               AA1,AA3,
     2               F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3               F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4               F13,F1A13,F2A13,F3A13,
     5               F111,F1A111,F2A111,F333,F1A333,F2A333,
     6               F113,F1A113,F2A113,F133,F1A133,F2A133,
     7               F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8               F1333,FA1333,F1133,FA1133,
     8               RE12 , RE32 , M1 , M2 , M3 , M ,
     9               U1 , U3 , U13 , V ,
     1               SYMM
C
      COMMON /INTEG/  ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1               RHOREF , VMIN , V0TYPE ,
     1               NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2               NSEPP2 , NSEQP1 , KSTYPA , LSTYPA
C
      COMMON /DIMEN/  MBASIS ,  V2MAX  , V2MXP1 ,
     1               JMAX   , JMAXP1 , MDIM   , NFSYM0 , NFASY0 ,
     2               NFSYMJ , NFASYJ
C
      COMMON /LSFIT/  PARMAX , NUMPAR , ISOMAX , IVAR
C
      COMMON /SYS/    THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1                     THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2                     VELLGT , PLANCK , AVOGNO , PI , PREC ,
     4                     NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 ,
     5                     NFIL6 , NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6                     NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7                     NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6                     ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7                     IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8                     NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER ,
     9                       NATTS , PRTINT
C
      COMMON/BCOEFF/
     1      B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      COMMON/CRCOEF/
     1      CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
C
      COMMON/MORSE/RMK,AAS
      COMMON/MODIM/NOBAS,MBASP1,LENIW
C
      KSTYP1=KSTYPA(1)
      KSTYP2=KSTYPA(2)
      LSTYP1=LSTYPA(1)
      LSTYP2=LSTYPA(2)
      DIMA=V2MXP1*LSTYP1
      IOSC1=1
      IOSC3=2
      NINDEX=0
      IF ( SYMM ) IOSC3=1
C
C 1. GENERATE MATRIX OF Y1
C
      CALL YONLY(IOSC1,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  2. GENERATE MATRIX OF Y3
C
      CALL YONLY(IOSC3,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  3. GENERATE MATRIX OF Y1*Y1
C
      CALL YY(IOSC1,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  4. GENERATE MATRIX OF Y3*Y3
C
      CALL YY(IOSC3,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C   5. GENERATE MATRIX OF Y1*Y3
C
      CALL Y1Y2(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  6. GENERATE MATRIX OF Y1*Y1*Y1
C
      CALL YYY(IOSC1,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  7. GENERATE MATRIX OF Y3*Y3*Y3
C
      CALL YYY(IOSC3,IW3,IW1,OVER,VMAT)
      CALL SIMTRN(VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  8. GENERATE MATRIX OF Y1*Y1*Y3
C
      CALL Y1Y1Y2(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  9. GENERATE MATRIX OF Y1*Y3*Y3
C
      CALL Y1Y1Y2(IOSC3,IOSC1,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  10. GENERATE MATRIX OF Y1*Y1*Y1*Y1
C
      CALL YYYY(IOSC1,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  11. GENERATE MATRIX OF Y3*Y3*Y3*Y3
C
      CALL YYYY(IOSC3,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  12. GENERATE MATRIX OF Y1*Y1*Y1*Y3
C
      CALL Y13Y2(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  13. GENERATE MATRIX OF Y1*Y3*Y3*Y3
C
      CALL Y13Y2(IOSC3,IOSC1,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  14. GENERATE MATRIX OF Y1*Y1*Y3*Y3
C
      CALL Y12Y22(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  15. GENERATE MATRIX OF Y1*P1+P1*Y1
C
      CALL YP(IOSC1,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  16. GENERATE MATRIX OF Y3*P3+P3*Y3
C
      CALL YP(IOSC3,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  17. GENERATE MATRIX OF P1*Y3
C
      CALL P1Y2(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  18. GENERATE MATRIX OF P3*Y1
C
      CALL P1Y2(IOSC3,IOSC1,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  19. GENERATE MATRIX OF Y1*Y1*P1+P1*Y1*Y1
C
      CALL Y2P(IOSC1,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  20. GENERATE MATRIX OF Y3*Y3*P3+P3*Y3*Y3
C
      CALL Y2P(IOSC3,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  21. GENERATE MATRIX OF P1*Y3*Y3
C
      CALL P1Y2Y2(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  22. GENERATE MATRIX OF P3*Y1*Y1
C
      CALL P1Y2Y2(IOSC3,IOSC1,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  23. GENERATE MATRIX OF (Y1*P1+P1*Y1)*Y3
C
      CALL YPY(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  24. GENERATE MATRIX OF (Y3*P3+P3*Y3)*Y1
C
      CALL YPY(IOSC3,IOSC1,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  25. GENERATE MATRIX OF Y1*Y1*Y1*P1+P1*Y1*Y1*Y1
C
      CALL Y3P(IOSC1,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  26. GENERATE MATRIX OF Y3*Y3*Y3*P3+P3*Y3*Y3*Y3
C
      CALL Y3P(IOSC3,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  27. GENERATE MATRIX OF P1*Y3*Y3*Y3
C
      CALL PY3(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  28. GENERATE MATRIX OF P3*Y1*Y1*Y1
C
      CALL PY3(IOSC3,IOSC1,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  29. GENERATE MATRIX OF (Y1*Y1*P1+P1*Y1*Y1)*Y3
C
      CALL Y2PY(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  30. GENERATE MATRIX OF (Y3*Y3*P3+P3*Y3*Y3)*Y1
C
      CALL Y2PY(IOSC3,IOSC1,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  31. GENERATE MATRIX OF (Y1*P1+P1*Y1)*Y3*Y3
C
      CALL YPY2(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  32. GENERATE MATRIX OF (Y3*P3+P3*Y3)*Y1
C
      CALL YPY2(IOSC3,IOSC1,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  33. GENERATE MATRIX OF P1*P3
C
      CALL P1P2(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  34. GENERATE MATRIX OF (Y1*P1+P1*Y1)*P3
C
      CALL PYYPP(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  35. GENERATE MATRIX OF (Y3*P3+P3*Y3)*P1
C
      CALL PYYPP(IOSC3,IOSC1,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  36. GENERATE MATRIX OF (Y1*Y1*P1+P1*Y1*Y1)*P3
C
      CALL YYPP(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  37. GENERATE MATRIX OF (Y3*Y3*P3+P3*Y3*Y3)*P1
C
      CALL YYPP(IOSC3,IOSC1,IW3,IW1,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C  38. GENERATE MATRIX OF (Y1*P1+P1*Y1)*(Y3*P3+P3*Y3)
C
      CALL YPPY(IOSC1,IOSC3,IW1,IW3,OVER,VMAT)
      CALL SIMTRN (VMAT,TMAT,SMAT,WMAT,NOBAS)
      CALL DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
C
C
C
      RETURN
      END
C
C
      SUBROUTINE SIMTRN ( A , U , B , W , N )
      IMPLICIT REAL*8 (A-H,O-Z)
      INTEGER N,I,J,K
      REAL*8 A(N,N),U(N,N),B(N,N),W(N,N),POM
C
      DO 20 I=1,N
      DO 20 J=1,N
      POM=0.0D0
      DO 10 K=1,N
10    POM=POM+U(K,I)*A(K,J)
20    W(J,I)=POM
C
      DO 40 I=1,N
      DO 40 J=1,N
      POM=0.0D0
      DO 30 K=1,N
30    POM=POM+W(K,I)*U(K,J)
40    B(I,J)=POM
C
      RETURN
      END
C
C
      SUBROUTINE DELK1 ( VALSYM , VALASY , SMAT   , HMAT   ,
     1                   NOFSRO , NOFSCO , NDIMRO , NDIMCO ,
     1                   JP1    , IRODIM , IEO    , ITAU   ,
     1                   INTSYM , INTASY , ISTOFF , JSTOFF ,
     1                   STOREM , NOPERA )
C
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 M1,M2,M3,M,U1,U3,U13,V,RHO,EPS,
     1      CR,SR,CSE,SNE,
     2      CRE,SRE,CORO,EPSP,EPSPP,EPSPPP
C
      REAL*8 AMASS(3,12)
C
      REAL*8 RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1       AA1,AA3,
     2       F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3       F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4       F13,F1A13,F2A13,F3A13,
     5       F111,F1A111,F2A111,F333,F1A333,F2A333,
     6       F113,F1A113,F2A113,F133,F1A133,F2A133,
     7       F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8       F1333,FA1333,F1133,FA1133,
     8       RE12 , RE32 , RHOREF , VMIN
C
      REAL*8 ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1      PREC
C
      REAL*8 THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1      THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2      VELLGT , PLANCK , AVOGNO , DEGRAD , RADDEG ,
     3      PI
C
      REAL*8   B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      REAL*8   CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
      INTEGER NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 , NFIL6 ,
     5       NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6       NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7       NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6       ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7       IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8       NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER,
     9       ISOMAX , NATTS  , V0TYPE , IVAR(55) , PARMAX ,
     1       NUMPAR , PRTINT
C
      INTEGER V1 ,V2, V3 , V2MXP1, V2P1,
     1       NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2       NSEPP2 , NSEQP1 , MBASIS ,
     3       MDIM , NFSYM0, NFASY0, NFSYMJ, NFASYJ,
     4       KSTYPA(2) , LSTYPA(2) , JMAX , V2MAX , JMAXP1
C
      INTEGER IQUANT(5,12)
C
      LOGICAL SYMM
C
      REAL*8 RMK(2),AAS(2)
      INTEGER NOBAS,MBASP1,LENIW
      INTEGER LENINT,IOSC1,IOSC3,I,J,IR,JL
      REAL*8 G,GC1,GC3,GC1113,GC3133,GC1133,GC3113
      REAL*8   SMAT(NOBAS,NOBAS),VALSYM(INTSYM),VALASY(INTASY),
     1       HMAT(IRODIM,IRODIM),STOREM(NOBAS,NOBAS,NOPERA)
      REAL*8  CONCOR,CONFC1,CONG11,CONG33,CONG13,CORHOE
      COMMON /ISOTOP/ IQUANT,AMASS
C
      COMMON /VALUES/ RHO,EPS,EPSP,EPSPP,EPSPPP,
     1               CR,SR,CSE,SNE,CRE,SRE,CORO
C
      COMMON /MOLCUL/ RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1               AA1,AA3,
     2               F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3               F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4               F13,F1A13,F2A13,F3A13,
     5               F111,F1A111,F2A111,F333,F1A333,F2A333,
     6               F113,F1A113,F2A113,F133,F1A133,F2A133,
     7               F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8               F1333,FA1333,F1133,FA1133,
     8               RE12 , RE32 , M1 , M2 , M3 , M ,
     9               U1 , U3 , U13 , V ,
     1               SYMM
C
      COMMON /INTEG/  ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1               RHOREF , VMIN , V0TYPE ,
     1               NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2               NSEPP2 , NSEQP1 , KSTYPA , LSTYPA
C
      COMMON /DIMEN/  MBASIS ,  V2MAX  , V2MXP1 ,
     1               JMAX   , JMAXP1 , MDIM   , NFSYM0 , NFASY0 ,
     2               NFSYMJ , NFASYJ
C
      COMMON /LSFIT/  PARMAX , NUMPAR , ISOMAX , IVAR
C
      COMMON /SYS/    THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1                     THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2                     VELLGT , PLANCK , AVOGNO , PI , PREC ,
     4                     NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 ,
     5                     NFIL6 , NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6                     NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7                     NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6                     ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7                     IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8                     NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER ,
     9                       NATTS , PRTINT
C
      COMMON/BCOEFF/
     1      B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      COMMON/CRCOEF/
     1      CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
C
      COMMON/MORSE/RMK,AAS
      COMMON/MODIM/NOBAS,MBASP1,LENIW
C
      CONCOR=PLANCK*AVOGNO*1.0D+16/(1.6D+01*PI*PI*VELLGT)
      CONYZ=CONCOR
      CONXR=CONCOR
      CONCOR=-CONCOR
      SQ2=DSQRT(2.0D+00)
      J=JP1-1
      REWIND NFIL11
      IF (.NOT. SYMM) REWIND NFIL12
C
      DO 780 K1P1=1,JP1
      DO 770 KDEL=-1,1,2
      K2P1=K1P1+KDEL
      IF (K2P1 .LT. 1 .OR. K2P1 .GT. JP1) GOTO 770
      IF (K1P1 .GT. K2P1) THEN
            XJK=DSQRT(DFLOAT(J*JP1-(K2P1-1)*K2P1))
      ELSE
            XJK=DSQRT(DFLOAT(J*JP1-(K1P1-1)*K1P1))
      ENDIF
      IF (K1P1 .EQ. 1 .OR. K2P1 .EQ. 1) XJK=SQ2*XJK
      XKK=DFLOAT(K1P1+K2P1-2)
      XXR=1.0D+00
      IF (K1P1 .LT. K2P1) XXR=-XXR
C
      DO 760 INDEX1=1,V2MXP1
      DO 750 INDEX2=1,V2MXP1
C
      READ (NFIL11) (VALSYM(L), L=1,25)
      IF (.NOT. SYMM) READ (NFIL12) (VALASY(L), L=1,22)
      IF (K1P1 .EQ. 1 .AND. MOD(J+ITAU,2) .NE. 0) GOTO 750
      IF (K2P1 .EQ. 1 .AND. MOD(J+ITAU,2) .NE. 0) GOTO 750
C
      NINDEX=0
C
      IF (MOD(K1P1,2) .NE. 0) THEN
            INDK1=(K1P1-1)/2
            IF (MOD(J+ITAU,2) .NE. 0) INDK1=INDK1-1
      ELSE
            INDK1=(K1P1-2)/2
      ENDIF
      IF (MOD(K2P1,2) .NE. 0) THEN
            INDK2=(K2P1-1)/2
            IF (MOD(J+ITAU,2) .NE. 0) INDK2=INDK2-1
      ELSE
            INDK2=(K2P1-2)/2
      ENDIF
      IROWOF=NOFSRO+INDK1*V2MXP1*NDIMRO+(INDEX1-1)*NDIMRO
      ICOLOF=NOFSCO+INDK2*V2MXP1*NDIMCO+(INDEX2-1)*NDIMCO
      JROWOF=NOFSRO+INDK2*V2MXP1*NDIMRO+(INDEX2-1)*NDIMRO
      JCOLOF=NOFSCO+INDK1*V2MXP1*NDIMCO+(INDEX1-1)*NDIMCO
C
      IF (MOD(K1P1,2) .EQ. IEO) GOTO 80
      GOTO 90
C
C  2A. TERMS CONTAINING Y1
C
80    CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR = CONXR*VALSYM(9)*XJK*XXR
      DO 820 JL=1,NDIMCO
      DO 820 IR=1,NDIMRO
820   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 3A. TERMS CONTAINING Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(8)*XJK*XXR
      ENDIF
      DO 840 JL=1,NDIMCO
      DO 840 IR=1,NDIMRO
840   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  4A. TERMS CONTAINING Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR = CONXR*VALSYM(10)*XJK*XXR
      DO 860 JL=1,NDIMCO
      DO 860 IR=1,NDIMRO
860   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 5A. TERMS CONTAINING Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(9)*XJK*XXR
      ENDIF
      DO 880 JL=1,NDIMCO
      DO 880 IR=1,NDIMRO
880   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 6A. TERMS CONTAINING Y1*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR = CONXR*VALSYM(11)*XJK*XXR
      DO 900 JL=1,NDIMCO
      DO 900 IR=1,NDIMRO
900   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  7A. TERMS CONTAINING Y1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR=CONXR*VALSYM(12)*XJK*XXR
      DO 920 JL=1,NDIMCO
      DO 920 IR=1,NDIMRO
920   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 8A. TERMS CONTAINING Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(10)*XJK*XXR
      ENDIF
      DO 940 JL=1,NDIMCO
      DO 940 IR=1,NDIMRO
940   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  9A. TERMS CONTAINING Y1*Y1*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR = CONXR*VALSYM(13)*XJK*XXR
      DO 960 JL=1,NDIMCO
      DO 960 IR=1,NDIMRO
960   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 10A. TERMS CONTAINING Y1*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(11)*XJK*XXR
      ENDIF
      DO 980 JL=1,NDIMCO
      DO 980 IR=1,NDIMRO
980   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  11A. TERMS CONTAINING Y1*Y1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR = CONXR*VALSYM(14)*XJK*XXR
      DO 1000 JL=1,NDIMCO
      DO 1000 IR=1,NDIMRO
1000  HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 12A. TERMS CONTAINING Y3*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(12)*XJK*XXR
      ENDIF
      DO 1020 JL=1,NDIMCO
      DO 1020 IR=1,NDIMRO
1020  HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  13A. TERMS CONTAINING Y1*Y1*Y1*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR = CONXR*VALSYM(15)*XJK*XXR
      DO 1040 JL=1,NDIMCO
      DO 1040 IR=1,NDIMRO
1040  HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 14A. TERMS CONTAINING Y1*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(13)*XJK*XXR
      ENDIF
      DO 1060 JL=1,NDIMCO
      DO 1060 IR=1,NDIMRO
1060  HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 15A. TERMS CONTAINING Y1*Y1*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      GXR = CONXR*VALSYM(16)*XJK*XXR
      DO 1080 JL=1,NDIMCO
      DO 1080 IR=1,NDIMRO
1080  HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL)
C
      GOTO 750
C
C  1. LEADING TERM (NOT DEPENDING ON STRETCHING COORDINATES)
C     (THIS TERM ONLY EXISTS FOR UNSYMMETRICAL MOLECULES).
C
90    CONTINUE
      IF (.NOT. SYMM) THEN
      G=CONYZ*VALASY(1)*XJK*XKK
      DO 100 IR=1,NDIMRO
100   HMAT(IROWOF+IR,ICOLOF+IR)=HMAT(IROWOF+IR,ICOLOF+IR)
     1                       +G
      ENDIF
C
C  2. TERMS CONTAINING Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONYZ*VALSYM( 1)*XJK*XKK
      GXR = CONXR*VALSYM(9)*XJK*XXR
      DO 120 JL=1,NDIMCO
      DO 120 IR=1,NDIMRO
120   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 3. TERMS CONTAINING Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                       G = CONYZ*VALASY( 2)*XJK*XKK
                     GXR = CONXR*VALASY(8)*XJK*XXR
      ENDIF
      DO 140 JL=1,NDIMCO
      DO 140 IR=1,NDIMRO
140   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  4. TERMS CONTAINING Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONYZ*VALSYM( 2)*XJK*XKK
      GXR = CONXR*VALSYM(10)*XJK*XXR
      DO 160 JL=1,NDIMCO
      DO 160 IR=1,NDIMRO
160   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 5. TERMS CONTAINING Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                       G = CONYZ*VALASY( 3)*XJK*XKK
                     GXR = CONXR*VALASY(9)*XJK*XXR
      ENDIF
      DO 180 JL=1,NDIMCO
      DO 180 IR=1,NDIMRO
180   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 6. TERMS CONTAINING Y1*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONYZ*VALSYM( 3)*XJK*XKK
      GXR = CONXR*VALSYM(11)*XJK*XXR
      DO 200 JL=1,NDIMCO
      DO 200 IR=1,NDIMRO
200   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  7. TERMS CONTAINING Y1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONYZ*VALSYM( 4)*XJK*XKK
      GXR=CONXR*VALSYM(12)*XJK*XXR
      DO 220 JL=1,NDIMCO
      DO 220 IR=1,NDIMRO
220   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 8. TERMS CONTAINING Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                      G = CONYZ*VALASY( 4)*XJK*XKK
                     GXR = CONXR*VALASY(10)*XJK*XXR
      ENDIF
      DO 240 JL=1,NDIMCO
      DO 240 IR=1,NDIMRO
240   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  9. TERMS CONTAINING Y1*Y1*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONYZ*VALSYM( 5)*XJK*XKK
      GXR = CONXR*VALSYM(13)*XJK*XXR
      DO 260 JL=1,NDIMCO
      DO 260 IR=1,NDIMRO
260   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 10. TERMS CONTAINING Y1*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                        G = CONYZ*VALASY( 5)*XJK*XKK
                     GXR = CONXR*VALASY(11)*XJK*XXR
      ENDIF
      DO 280 JL=1,NDIMCO
      DO 280 IR=1,NDIMRO
280   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  11. TERMS CONTAINING Y1*Y1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONYZ*VALSYM( 6)*XJK*XKK
      GXR = CONXR*VALSYM(14)*XJK*XXR
      DO 300 JL=1,NDIMCO
      DO 300 IR=1,NDIMRO
300   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 12. TERMS CONTAINING Y3*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                        G = CONYZ*VALASY( 6)*XJK*XKK
                     GXR = CONXR*VALASY(12)*XJK*XXR
      ENDIF
      DO 320 JL=1,NDIMCO
      DO 320 IR=1,NDIMRO
320   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  13. TERMS CONTAINING Y1*Y1*Y1*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONYZ*VALSYM( 7)*XJK*XKK
      GXR = CONXR*VALSYM(15)*XJK*XXR
      DO 340 JL=1,NDIMCO
      DO 340 IR=1,NDIMRO
340   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 14. TERMS CONTAINING Y1*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                       G = CONYZ*VALASY( 7)*XJK*XKK
                     GXR = CONXR*VALASY(13)*XJK*XXR
      ENDIF
      DO 360 JL=1,NDIMCO
      DO 360 IR=1,NDIMRO
360   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 15. TERMS CONTAINING Y1*Y1*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONYZ*VALSYM( 8)*XJK*XKK
      GXR = CONXR*VALSYM(16)*XJK*XXR
      DO 380 JL=1,NDIMCO
      DO 380 IR=1,NDIMRO
380   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 16. TERMS CONTAINING Y1*P1+P1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*XJK*XXR*VALSYM(17)
      DO 400 JL=1,NDIMCO
      DO 400 IR=1,NDIMRO
400   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 17. TERMS CONTAINING Y3*P3+P3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(15)
      DO 420 JL=1,NDIMCO
      DO 420 IR=1,NDIMRO
420   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 18. TERMS CONTAINING Y3*P1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = 2.0D+00*CONCOR*XJK*XXR*VALSYM(18)
      DO 440 JL=1,NDIMCO
      DO 440 IR=1,NDIMRO
440   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 19. TERMS CONTAINING Y1*P3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = -G
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*XJK*XXR*VALASY(14)
      DO 460 JL=1,NDIMCO
      DO 460 IR=1,NDIMRO
460   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 20. TERMS CONTAINING Y1*Y1*P1+P1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*XJK*XXR*VALSYM(19)
      DO 480 JL=1,NDIMCO
      DO 480 IR=1,NDIMRO
480   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 21. TERMS CONTAINING Y3*Y3*P3+P3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(17)
      DO 500 JL=1,NDIMCO
      DO 500 IR=1,NDIMRO
500   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 22. TERMS CONTAINING P1*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = 2.0D+00*CONCOR*XJK*XXR*VALSYM(20)
      DO 520 JL=1,NDIMCO
      DO 520 IR=1,NDIMRO
520   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 23. TERMS CONTAINING P3*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = -G
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*XJK*XXR*VALASY(16)
      DO 540 JL=1,NDIMCO
      DO 540 IR=1,NDIMRO
540   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 24. TERMS CONTAINING (Y1*P1+P1*Y1)*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*XJK*XXR*VALSYM(21)
      DO 560 JL=1,NDIMCO
      DO 560 IR=1,NDIMRO
560   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 25. TERMS CONTAINING (Y3*P3+P3*Y3)*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(18)
      DO 580 JL=1,NDIMCO
      DO 580 IR=1,NDIMRO
580   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 26. TERMS CONTAINING Y1*Y1*Y1*P1+P1*Y1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*XJK*XXR*VALSYM(22)
      DO 600 JL=1,NDIMCO
      DO 600 IR=1,NDIMRO
600   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 27. TERMS CONTAINING Y3*Y3*Y3*P3+P3*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(20)
      DO 620 JL=1,NDIMCO
      DO 620 IR=1,NDIMRO
620   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 28. TERMS CONTAINING P1*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = 2.0D+00*CONCOR*XJK*XXR*VALSYM(23)
      DO 640 JL=1,NDIMCO
      DO 640 IR=1,NDIMRO
640   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 29. TERMS CONTAINING P3*Y1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = -G
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*XJK*XXR*VALASY(19)
      DO 660 JL=1,NDIMCO
      DO 660 IR=1,NDIMRO
660   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 30. TERMS CONTAINING (Y1*Y1*P1+P1*Y1*Y1)*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*XJK*XXR*VALSYM(24)
      DO 680 JL=1,NDIMCO
      DO 680 IR=1,NDIMRO
680   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 31. TERMS CONTAINING (Y3*Y3*P3+P3*Y3*Y3)*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(22)
      DO 700 JL=1,NDIMCO
      DO 700 IR=1,NDIMRO
700   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 32. TERMS CONTAINING (Y1*P1+P1*Y1)*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = CONCOR*XJK*XXR*VALSYM(25)
      DO 720 JL=1,NDIMCO
      DO 720 IR=1,NDIMRO
720   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 33. TERMS CONTAINING (Y3*P3+P3*Y3)*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(21)
      DO 740 JL=1,NDIMCO
      DO 740 IR=1,NDIMRO
740   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
750   CONTINUE
760   CONTINUE
770   CONTINUE
780   CONTINUE
      RETURN
      END
C
C
      SUBROUTINE DELK2 ( VALSYM , VALASY , SMAT   , HMAT   ,
     1                   NOFSRO , NOFSCO , NDIMRO , NDIMCO ,
     1                   JP1    , IRODIM , IEO    , ITAU   ,
     1                   INTSYM , INTASY , ISTOFF , JSTOFF ,
     1                   STOREM , NOPERA )
C
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 M1,M2,M3,M,U1,U3,U13,V,RHO,EPS,
     1      CR,SR,CSE,SNE,
     2      CRE,SRE,CORO,EPSP,EPSPP,EPSPPP
C
      REAL*8 AMASS(3,12)
C
      REAL*8 RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1       AA1,AA3,
     2       F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3       F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4       F13,F1A13,F2A13,F3A13,
     5       F111,F1A111,F2A111,F333,F1A333,F2A333,
     6       F113,F1A113,F2A113,F133,F1A133,F2A133,
     7       F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8       F1333,FA1333,F1133,FA1133,
     8       RE12 , RE32 , RHOREF , VMIN
C
      REAL*8 ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1      PREC
C
      REAL*8 THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1      THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2      VELLGT , PLANCK , AVOGNO , DEGRAD , RADDEG ,
     3      PI
C
      REAL*8   B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      REAL*8   CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
      INTEGER NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 , NFIL6 ,
     5       NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6       NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7       NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6       ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7       IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8       NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER,
     9       ISOMAX , NATTS  , V0TYPE , IVAR(55) , PARMAX ,
     1       NUMPAR , PRTINT
C
      INTEGER V1 ,V2, V3 , V2MXP1, V2P1,
     1       NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2       NSEPP2 , NSEQP1 , MBASIS ,
     3       MDIM , NFSYM0, NFASY0, NFSYMJ, NFASYJ,
     4       KSTYPA(2) , LSTYPA(2) , JMAX , V2MAX , JMAXP1
C
      INTEGER IQUANT(5,12)
C
      LOGICAL SYMM
C
      REAL*8 RMK(2),AAS(2)
      INTEGER NOBAS,MBASP1,LENIW
      INTEGER LENINT,IOSC1,IOSC3,I,J,IR,JL
      REAL*8 G,GC1,GC3,GC1113,GC3133,GC1133,GC3113
      REAL*8   SMAT(NOBAS,NOBAS),VALSYM(INTSYM),VALASY(INTASY),
     1       HMAT(IRODIM,IRODIM),STOREM(NOBAS,NOBAS,NOPERA)
      REAL*8  CONCOR,CONFC1,CONG11,CONG33,CONG13,CORHOE
      COMMON /ISOTOP/ IQUANT,AMASS
C
      COMMON /VALUES/ RHO,EPS,EPSP,EPSPP,EPSPPP,
     1               CR,SR,CSE,SNE,CRE,SRE,CORO
C
      COMMON /MOLCUL/ RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1               AA1,AA3,
     2               F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3               F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4               F13,F1A13,F2A13,F3A13,
     5               F111,F1A111,F2A111,F333,F1A333,F2A333,
     6               F113,F1A113,F2A113,F133,F1A133,F2A133,
     7               F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8               F1333,FA1333,F1133,FA1133,
     8               RE12 , RE32 , M1 , M2 , M3 , M ,
     9               U1 , U3 , U13 , V ,
     1               SYMM
C
      COMMON /INTEG/  ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1               RHOREF , VMIN , V0TYPE ,
     1               NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2               NSEPP2 , NSEQP1 , KSTYPA , LSTYPA
C
      COMMON /DIMEN/  MBASIS ,  V2MAX  , V2MXP1 ,
     1               JMAX   , JMAXP1 , MDIM   , NFSYM0 , NFASY0 ,
     2               NFSYMJ , NFASYJ
C
      COMMON /LSFIT/  PARMAX , NUMPAR , ISOMAX , IVAR
C
      COMMON /SYS/    THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1                     THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2                     VELLGT , PLANCK , AVOGNO , PI , PREC ,
     4                     NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 ,
     5                     NFIL6 , NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6                     NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7                     NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6                     ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7                     IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8                     NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER ,
     9                       NATTS , PRTINT
C
      COMMON/BCOEFF/
     1      B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      COMMON/CRCOEF/
     1      CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
C
      COMMON/MORSE/RMK,AAS
      COMMON/MODIM/NOBAS,MBASP1,LENIW
C
      CONXX=-PLANCK*AVOGNO*1.0D+16/(3.2D+01*PI*PI*VELLGT)
      SQ2=DSQRT(2.0D+00)
      J=JP1-1
      REWIND NFIL13
      IF (.NOT. SYMM) REWIND NFIL14
C
      DO 460 K1P1=1,JP1
      DO 440 KDEL=-2,2,4
      K2P1=K1P1+KDEL
      IF (K2P1 .LT. 1 .OR. K2P1 .GT. JP1) GOTO 440
      IF (K1P1 .GT. K2P1) THEN
       XJK=DSQRT(DFLOAT((J*JP1-(K2P1-1)*K2P1)*(J*JP1-K2P1*(K2P1+1))))
      ELSE
       XJK=DSQRT(DFLOAT((J*JP1-(K1P1-1)*K1P1)*(J*JP1-K1P1*(K1P1+1))))
      ENDIF
C
      IF (K1P1 .EQ. 1 .OR. K2P1 .EQ. 1) XJK=SQ2*XJK
      DO 420 INDEX1=1,V2MXP1
      DO 400 INDEX2=1,V2MXP1
C
      READ (NFIL13) (VALSYM(L), L=1,18)
      IF (.NOT. SYMM) READ (NFIL14) (VALASY(L), L=1,12)
      IF (MOD(K1P1,2) .EQ. IEO) GOTO 400
      IF (K1P1 .EQ. 1 .AND. MOD(J+ITAU,2) .NE. 0) GOTO 400
      IF (K2P1 .EQ. 1 .AND. MOD(J+ITAU,2) .NE. 0) GOTO 400
C
      NINDEX=0
C
      IF (MOD(K1P1,2) .NE. 0) THEN
            INDK1=(K1P1-1)/2
            IF (MOD(J+ITAU,2) .NE. 0) INDK1=INDK1-1
      ELSE
            INDK1=(K1P1-2)/2
      ENDIF
      IF (MOD(K2P1,2) .NE. 0) THEN
            INDK2=(K2P1-1)/2
            IF (MOD(J+ITAU,2) .NE. 0) INDK2=INDK2-1
      ELSE
            INDK2=(K2P1-2)/2
      ENDIF
      IROWOF=NOFSRO+INDK1*V2MXP1*NDIMRO+(INDEX1-1)*NDIMRO
      ICOLOF=NOFSCO+INDK2*V2MXP1*NDIMCO+(INDEX2-1)*NDIMCO
C
C  1. LEADING TERM (NOT DEPENDING ON STRETCHING COORDINATES)
C
      G =  CONXX*(VALSYM( 1)-VALSYM(10))*XJK
      DO 100 IR=1,NDIMRO
100   HMAT(IROWOF+IR,ICOLOF+IR)=HMAT(IROWOF+IR,ICOLOF+IR)
     1                       +G
C
C  2. TERMS CONTAINING Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONXX*(VALSYM( 2)-VALSYM(11))*XJK
      DO 120 JL=1,NDIMCO
      DO 120 IR=1,NDIMRO
120   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 3. TERMS CONTAINING Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM)
     2                 G = CONXX*(VALASY( 1)-VALASY( 7))*XJK
      DO 140 JL=1,NDIMCO
      DO 140 IR=1,NDIMRO
140   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  4. TERMS CONTAINING Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONXX*(VALSYM( 3)-VALSYM(12))*XJK
      DO 160 JL=1,NDIMCO
      DO 160 IR=1,NDIMRO
160   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 5. TERMS CONTAINING Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM)
     2                 G = CONXX*(VALASY( 2)-VALASY( 8))*XJK
      DO 180 JL=1,NDIMCO
      DO 180 IR=1,NDIMRO
180   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 6. TERMS CONTAINING Y1*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONXX*(VALSYM( 4)-VALSYM(13))*XJK
      DO 200 JL=1,NDIMCO
      DO 200 IR=1,NDIMRO
200   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  7. TERMS CONTAINING Y1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONXX*(VALSYM( 5)-VALSYM(14))*XJK
      DO 220 JL=1,NDIMCO
      DO 220 IR=1,NDIMRO
220   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 8. TERMS CONTAINING Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM)
     2                G = CONXX*(VALASY( 3)-VALASY( 9))*XJK
      DO 240 JL=1,NDIMCO
      DO 240 IR=1,NDIMRO
240   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  9. TERMS CONTAINING Y1*Y1*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONXX*(VALSYM( 6)-VALSYM(15))*XJK
      DO 260 JL=1,NDIMCO
      DO 260 IR=1,NDIMRO
260   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 10. TERMS CONTAINING Y1*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM)
     2                  G = CONXX*(VALASY( 4)-VALASY(10))*XJK
      DO 280 JL=1,NDIMCO
      DO 280 IR=1,NDIMRO
280   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  11. TERMS CONTAINING Y1*Y1*Y1*Y1
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONXX*(VALSYM( 7)-VALSYM(16))*XJK
      DO 300 JL=1,NDIMCO
      DO 300 IR=1,NDIMRO
300   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 12. TERMS CONTAINING Y3*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM)
     2                  G = CONXX*(VALASY( 5)-VALASY(11))*XJK
      DO 320 JL=1,NDIMCO
      DO 320 IR=1,NDIMRO
320   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C  13. TERMS CONTAINING Y1*Y1*Y1*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONXX*(VALSYM( 8)-VALSYM(17))*XJK
      DO 340 JL=1,NDIMCO
      DO 340 IR=1,NDIMRO
340   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 14. TERMS CONTAINING Y1*Y3*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IF (.NOT. SYMM)
     2                 G = CONXX*(VALASY( 6)-VALASY(12))*XJK
      DO 360 JL=1,NDIMCO
      DO 360 IR=1,NDIMRO
360   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
C
C 15. TERMS CONTAINING Y1*Y1*Y3*Y3
C
      CALL GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
       G = CONXX*(VALSYM( 9)-VALSYM(18))*XJK
      DO 380 JL=1,NDIMCO
      DO 380 IR=1,NDIMRO
380   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL)
400   CONTINUE
420   CONTINUE
440   CONTINUE
460   CONTINUE
      RETURN
      END
C
C
      SUBROUTINE DEPOSI ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 SMAT(NOBAS,NOBAS),STOREM(NOBAS,NOBAS,NOPERA)
      NINDEX=NINDEX+1
      DO 20 III=1,NOBAS
      DO 20 JJJ=1,NOBAS
20    STOREM(JJJ,III,NINDEX)=SMAT(JJJ,III)
      RETURN
      END
C
C
      SUBROUTINE GETBCK ( SMAT , STOREM , NOBAS , NOPERA , NINDEX )
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 SMAT(NOBAS,NOBAS),STOREM(NOBAS,NOBAS,NOPERA)
      NINDEX=NINDEX+1
      DO 20 III=1,NOBAS
      DO 20 JJJ=1,NOBAS
20    SMAT(JJJ,III)=STOREM(JJJ,III,NINDEX)
      RETURN
      END
